// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // DIRECT_URL = non-pooled Neon connection required for prisma migrate
    // Runtime queries use DATABASE_URL (pooled) via PrismaPg adapter in src/lib/db.ts
    url: process.env["DIRECT_URL"],
  },
});
